import type { Metadata } from "next";
import { Coming_Soon } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import "react-big-calendar/lib/css/react-big-calendar.css";
import { Theme } from "@radix-ui/themes";
import { Footer, Header } from "./components";

const comingSoon = Coming_Soon({
	weight: "400",
	variable: "--font-coming-soon",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={comingSoon.variable}>
			<body className={`${comingSoon.className} antialiased`}>
				<Theme
					appearance="light"
					style={{ fontFamily: "var(--font-coming-soon)" }}
					accentColor="lime"
				>
					<div style={{ backgroundColor: "var(--lime-1)" }}>
						<Header />
						{children}
						<Footer />
					</div>
				</Theme>
			</body>
		</html>
	);
}
